### ISSUE TITLE
Hmm, markdown doesn't seem to persist in pages

### ISSUE THREAD

**Issue by lonelyjoeparker** [RBGKew/rbgkew.github.io#1]
e.g. compare https://github.com/RBGKew/rbgkew.github.io/blob/master/_posts/2015-08-04-another-sample-post.md

with https://rbgkew.github.io/2015/08/04/another-sample-post.html

**Comment by lonelyjoeparker** [comment]
Actually I meant 'work' not persist.. realised it wasn't working in the other post either, at least for headers https://rbgkew.github.io/2015/06/25/bats-and-genome-convergence-pipeline-have-moved.html

**Comment by jiacona** [comment]
Ah yes, the joys of inconsistencies between markdown implementations. You are using the Github flavoured markdown variant which the default Jekyll doesn't support. I tweaked the configuration a bit to mirror (I think) Github's settings.

**Comment by lonelyjoeparker** [comment]
Sweet! Cheers John :)
